[INFO -- 2018-09-25 05:03:47]
Starting flip_value script
version: 1.1
[INFO -- 2018-09-25 05:03:47]
Initialization strings:
[INFO -- 2018-09-25 05:03:47]
(1) file /tmp/knapsack/ga
[INFO -- 2018-09-25 05:03:47]
initSignal:1
[INFO -- 2018-09-25 05:03:47]
endSignal:3.5
[INFO -- 2018-09-25 05:03:47]
faultModel:3
[EXCEPTION -- 2018-09-25 05:03:48]
pythonException: 19
[EXCEPTION -- 2018-09-25 05:03:48]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-09-25 05:03:48]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[INFO -- 2018-09-25 05:03:48]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7490f5d in __GI_abort () at abort.c:90
#2  0x00007ffff7ae1095 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7adec86 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7adecd1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7adef14 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7adf49c in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000055555555a070 in __gnu_cxx::new_allocator<int>::allocate (this=0x7fffffffd950, __n=23456248634092) at /usr/include/c++/7/ext/new_allocator.h:111
#8  0x0000555555559587 in std::allocator_traits<std::allocator<int> >::allocate (__a=..., __n=23456248634092) at /usr/include/c++/7/bits/alloc_traits.h:436
#9  0x0000555555558554 in std::_Vector_base<int, std::allocator<int> >::_M_allocate (this=0x7fffffffd950, __n=23456248634092) at /usr/include/c++/7/bits/stl_vector.h:172
#10 0x000055555555712e in std::vector<int, std::allocator<int> >::_M_allocate_and_copy<__gnu_cxx::__normal_iterator<int const*, std::vector<int, std::allocator<int> > > > (this=0x7fffffffd950, __n=23456248634092, __first=non-dereferenceable iterator for std::vector, __last=816) at /usr/include/c++/7/bits/stl_vector.h:1260
#11 0x000055555555617b in std::vector<int, std::allocator<int> >::operator= (this=0x7fffffffd950, __x=std::vector of length 23456248634092, capacity 23456248634092 = {...}) at /usr/include/c++/7/bits/vector.tcc:206
#12 0x000055555555516a in crossover (pai=std::vector of length 23456248634092, capacity 23456248634092 = {...}, mae=std::vector of length 200, capacity 200 = {...}, filho1=std::vector of length 0, capacity 0, filho2=std::vector of length 0, capacity 0) at knapsackga.cpp:76
#13 0x000055555555548d in genetic_algorithm () at knapsackga.cpp:104
#14 0x00005555555558d7 in main () at knapsackga.cpp:137

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Fliping a bit of the value pointed by a reference
Fliping value of field: std::_Vector_base<int, std::allocator<int> >
Fliping value of field: _M_impl
Fliping value of field: _M_start
Fliping a bit of the pointer
Memory content before bitflip:0x000x000x000x000x000x000x000x00
Fault Model: Zero bit-flip
base address to flip value: 0x7fffffffd970
address max offset: 8
Memory content after  bitflip:0x000x000x000x000x000x000x000x00
frame name: crossover
symbol name: filho2
symbol filename: knapsackga.cpp
symbol line: 71
value: std::vector of length 0, capacity 0
value address: 0x7fffffffd970
Type: A reference type.
Type sizeof: 8

[INFO -- 2018-09-25 05:03:48]
Fault Injection Successful after 1.8386375904083252s
[INFO -- 2018-09-25 05:03:48]
event type: exit
[EXCEPTION -- 2018-09-25 05:03:48]
exit code: no exit code available
