[INFO -- 2018-12-08 03:08:10]
Starting flip_value script
version: 1.1
[INFO -- 2018-12-08 03:08:10]
Initialization strings:
[INFO -- 2018-12-08 03:08:10]
(1) file /tmp/knapsack/sa
[INFO -- 2018-12-08 03:08:10]
initSignal:0
[INFO -- 2018-12-08 03:08:10]
endSignal:9
[INFO -- 2018-12-08 03:08:10]
faultModel:1
[EXCEPTION -- 2018-12-08 03:08:14]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-12-08 03:08:15]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-12-08 03:08:16]
Backtrace BEGIN:
#0  std::_Destroy_aux<true>::__destroy<int*> () at /usr/include/c++/7/bits/stl_construct.h:117
#1  0x0000555555556801 in std::_Destroy<int*> (__first=0x5555557727c0, __last=0x555555772ae0) at /usr/include/c++/7/bits/stl_construct.h:137
#2  0x0000555555555faf in std::_Destroy<int*, int> (__first=0x5555557727c0, __last=0x555555772ae0) at /usr/include/c++/7/bits/stl_construct.h:206
#3  0x000055555555593d in std::vector<int, std::allocator<int> >::~vector (this=0x7fffffffd740, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:434
#4  0x0000555555555468 in simulated_annealing () at knapsacksa.cpp:89
#5  0x0000555555555658 in main () at knapsacksa.cpp:146

112	  template<>
113	    struct _Destroy_aux<true>
114	    {
115	      template<typename _ForwardIterator>
116	        static void
117	        __destroy(_ForwardIterator, _ForwardIterator) { }
118	    };
119	
120	  /**
121	   * Destroy a range of objects.  If the value_type of the object has

Backtrace END
Memory content before bitflip:0x310xfb0x080x00
Fault Model: Double bit-flip
base address to flip value: 0x555555759034 
address max offset: 4
Memory content after  bitflip:0x310xd90x080x00
frame name: std::_Destroy_aux<true>::__destroy<int*>
symbol name: W2
symbol filename: knapsacksa.cpp
symbol line: 13
value: 579889
value address: 0x555555759034 <W2>
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2018-12-08 03:08:16]
Fault Injection Successful after 6.117678880691528s
[INFO -- 2018-12-08 03:08:16]
event type: exit
[EXCEPTION -- 2018-12-08 03:08:16]
exit code: no exit code available
