[INFO -- 2018-12-08 22:53:28]
Starting flip_value script
version: 1.1
[INFO -- 2018-12-08 22:53:28]
Initialization strings:
[INFO -- 2018-12-08 22:53:28]
(1) file /tmp/knapsack/ga
[INFO -- 2018-12-08 22:53:28]
initSignal:1
[INFO -- 2018-12-08 22:53:28]
endSignal:8
[INFO -- 2018-12-08 22:53:28]
faultModel:2
[EXCEPTION -- 2018-12-08 22:53:29]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[EXCEPTION -- 2018-12-08 22:53:29]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-12-08 22:53:30]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7490f5d in __GI_abort () at abort.c:90
#2  0x00007ffff74d928d in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7600528 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff74e7650 in malloc_printerr (ar_ptr=0x0, ptr=<optimized out>, str=0x7ffff7600840 "munmap_chunk(): invalid pointer", action=<optimized out>) at malloc.c:5426
#4  munmap_chunk (p=<optimized out>) at malloc.c:2877
#5  __GI___libc_free (mem=<optimized out>) at malloc.c:3138
#6  0x0000555555559846 in __gnu_cxx::new_allocator<int>::deallocate (this=0x55555575f070 <wt>, __p=0x555555777cb5) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x0000555555558802 in std::allocator_traits<std::allocator<int> >::deallocate (__a=..., __p=0x555555777cb5, __n=238) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x0000555555557370 in std::_Vector_base<int, std::allocator<int> >::_M_deallocate (this=0x55555575f070 <wt>, __p=0x555555777cb5, __n=238) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x0000555555556b87 in std::_Vector_base<int, std::allocator<int> >::~_Vector_base (this=0x55555575f070 <wt>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:162
#10 0x0000555555555ed7 in std::vector<int, std::allocator<int> >::~vector (this=0x55555575f070 <wt>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#11 0x00007ffff7493ec0 in __run_exit_handlers (status=0, listp=0x7ffff78326f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:83
#12 0x00007ffff7493f1a in __GI_exit (status=<optimized out>) at exit.c:105
#13 0x0000555555554fcb in exit_gracefully () at knapsackga.cpp:26
#14 0x0000555555555165 in cost (solution=std::vector of length 200, capacity 200 = {...}) at knapsackga.cpp:48
#15 0x000055555555589e in genetic_algorithm () at knapsackga.cpp:138
#16 0x0000555555555b6c in main () at knapsackga.cpp:165

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Memory content before bitflip:0x2f0x060x000x00
Fault Model: Random bit-flip
base address to flip value: 0x7fffffffd874
address max offset: 4
Memory content after  bitflip:0x790xb60x9e0x80
frame name: genetic_algorithm
symbol name: g
symbol filename: knapsackga.cpp
symbol line: 116
value: -2137082247
value address: 0x7fffffffd874
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2018-12-08 22:53:30]
Fault Injection Successful after 2.1266708374023438s
[INFO -- 2018-12-08 22:53:30]
event type: exit
[EXCEPTION -- 2018-12-08 22:53:30]
exit code: no exit code available
