[INFO -- 2018-12-09 01:41:02]
Starting flip_value script
version: 1.1
[INFO -- 2018-12-09 01:41:02]
Initialization strings:
[INFO -- 2018-12-09 01:41:02]
(1) file /tmp/knapsack/ga
[INFO -- 2018-12-09 01:41:02]
initSignal:1
[INFO -- 2018-12-09 01:41:02]
endSignal:8
[INFO -- 2018-12-09 01:41:02]
faultModel:1
[EXCEPTION -- 2018-12-09 01:41:03]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-12-09 01:41:03]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-12-09 01:41:03]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7490f5d in __GI_abort () at abort.c:90
#2  0x00007ffff74d928d in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7600528 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff74e064a in malloc_printerr (action=<optimized out>, str=0x7ffff75fceae "free(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5426
#4  0x00007ffff74e273e in _int_free (av=0x7ffff7832c20 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4175
#5  0x00007ffff74e744e in __GI___libc_free (mem=<optimized out>) at malloc.c:3145
#6  0x0000555555559846 in __gnu_cxx::new_allocator<int>::deallocate (this=0x55555575f030 <val>, __p=0x55555577745f) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x0000555555558802 in std::allocator_traits<std::allocator<int> >::deallocate (__a=..., __p=0x55555577745f, __n=252) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x0000555555557370 in std::_Vector_base<int, std::allocator<int> >::_M_deallocate (this=0x55555575f030 <val>, __p=0x55555577745f, __n=252) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x0000555555556b87 in std::_Vector_base<int, std::allocator<int> >::~_Vector_base (this=0x55555575f030 <val>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:162
#10 0x0000555555555ed7 in std::vector<int, std::allocator<int> >::~vector (this=0x55555575f030 <val>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#11 0x00007ffff7493ec0 in __run_exit_handlers (status=0, listp=0x7ffff78326f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:83
#12 0x00007ffff7493f1a in __GI_exit (status=<optimized out>) at exit.c:105
#13 0x0000555555554fcb in exit_gracefully () at knapsackga.cpp:26
#14 0x0000555555555165 in cost (solution=std::vector of length 200, capacity 200 = {...}) at knapsackga.cpp:48
#15 0x000055555555589e in genetic_algorithm () at knapsackga.cpp:138
#16 0x0000555555555b6c in main () at knapsackga.cpp:165

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Fliping a bit of the value pointed by a reference
Fliping value of field: std::_Vector_base<int, std::allocator<int> >
Fliping value of field: _M_impl
Fliping value of field: _M_start
Fliping a bit of the value pointed by a pointer
Memory content before bitflip:0x000x000x000x00
Fault Model: Double bit-flip
base address to flip value: 0x555555785bc0
address max offset: 4
Memory content after  bitflip:0x000x000x000x28
frame name: cost
symbol name: solution
symbol filename: knapsackga.cpp
symbol line: 33
value: std::vector of length 200, capacity 200 = {671088640, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1...}
value address: 0x55555578ac50
Type: A reference type.
Type sizeof: 8

[INFO -- 2018-12-09 01:41:03]
Fault Injection Successful after 1.9675116539001465s
[INFO -- 2018-12-09 01:41:04]
event type: exit
[EXCEPTION -- 2018-12-09 01:41:04]
exit code: no exit code available
